# Generated by Django 5.0.3 on 2024-03-17 17:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tech_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Event Name')),
                ('dec', ckeditor.fields.RichTextField()),
                ('fc', models.CharField(max_length=50, verbose_name='Faculty Cordinator')),
                ('fcph', models.CharField(max_length=50, verbose_name='Faculty Cordinator Phono')),
                ('ec1', models.CharField(max_length=50, verbose_name='Event Cordinator 1')),
                ('ec1ph', models.CharField(max_length=50, verbose_name='Event Cordinator 1 phone number')),
                ('ec2', models.CharField(max_length=50, verbose_name='Event Cordinator 2')),
                ('ec2ph', models.CharField(max_length=50, verbose_name='Event Cordinator 2 phono number')),
                ('venue', models.CharField(max_length=50, verbose_name='Venue')),
                ('ef', models.CharField(max_length=50, verbose_name='Entry Fee')),
                ('prize1st', models.CharField(max_length=50, verbose_name='Price 1st')),
                ('prize2nd', models.CharField(max_length=50, verbose_name='Price 2nd')),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
            ],
        ),
    ]
