# Generated by Django 5.0.3 on 2024-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_event',
            name='img',
            field=models.ImageField(default=1, upload_to='event/banner', verbose_name='banner 500 * 341'),
            preserve_default=False,
        ),
    ]
