# Generated by Django 5.0.3 on 2024-03-17 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_tech_event_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech_event_register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('ph', models.CharField(max_length=250, verbose_name='Phone number')),
                ('collegename', models.CharField(max_length=250, verbose_name='College Name')),
                ('usn', models.CharField(max_length=250, verbose_name='USN')),
                ('paymentproof', models.ImageField(upload_to='event/PaymentProof', verbose_name='Payment Proof')),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
            ],
        ),
    ]
