# Generated by Django 5.0.3 on 2024-03-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0003_tech_event_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_event_register',
            name='event',
            field=models.CharField(default=1, max_length=250, verbose_name='Event name'),
            preserve_default=False,
        ),
    ]
