# Generated by Django 5.0.3 on 2024-03-17 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0004_tech_event_register_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_event_register',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical.tech_event', verbose_name='Event Name'),
        ),
    ]
