# Generated by Django 5.0.3 on 2024-03-17 18:55

import technical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0005_alter_tech_event_register_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_event_register',
            name='id',
            field=models.UUIDField(default=technical.models.generate_unique_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
