# Generated by Django 5.0.3 on 2024-03-17 19:05

import technical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0006_alter_tech_event_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_event_register',
            name='id',
            field=models.CharField(default=technical.models.generate_unique_id_with_check, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
