# Generated by Django 5.0.3 on 2024-03-17 19:42

import ckeditor.fields
import django.db.models.deletion
import non_technical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='non_tech_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Event Name')),
                ('img', models.ImageField(upload_to='event/banner', verbose_name='banner 500 * 341')),
                ('dec', ckeditor.fields.RichTextField()),
                ('fc', models.CharField(max_length=50, verbose_name='Faculty Cordinator')),
                ('fcph', models.CharField(max_length=50, verbose_name='Faculty Cordinator Phono')),
                ('ec1', models.CharField(max_length=50, verbose_name='Event Cordinator 1')),
                ('ec1ph', models.CharField(max_length=50, verbose_name='Event Cordinator 1 phone number')),
                ('ec2', models.CharField(max_length=50, verbose_name='Event Cordinator 2')),
                ('ec2ph', models.CharField(max_length=50, verbose_name='Event Cordinator 2 phono number')),
                ('venue', models.CharField(max_length=50, verbose_name='Venue')),
                ('ef', models.CharField(max_length=50, verbose_name='Entry Fee')),
                ('prize1st', models.CharField(max_length=50, verbose_name='Price 1st')),
                ('prize2nd', models.CharField(max_length=50, verbose_name='Price 2nd')),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='non_tech_event_register',
            fields=[
                ('id', models.CharField(default=non_technical.models.generate_unique_id_with_check, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('ph', models.CharField(max_length=250, verbose_name='Phone number')),
                ('collegename', models.CharField(max_length=250, verbose_name='College Name')),
                ('usn', models.CharField(max_length=250, verbose_name='USN')),
                ('paymentproof', models.ImageField(upload_to='event/PaymentProof', verbose_name='Payment Proof')),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='non_technical.non_tech_event', verbose_name='Event Name')),
            ],
        ),
    ]
